server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ewallet_auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  secret: ${JWT_SECRET:mypay-super-secret-key-256-bits-long-for-hmac-sha256-algorithm-secure}
  expiration-ms: 900000
  refresh-expiration-ms: 604800000
